const REQ_WEATHER_DATA = 'REQ_WEATHER_DATA';
const REQ_WEATHER_DATA_SUCCESS = 'REQ_WEATHER_DATA_SUCCESS';
const REQ_WEATHER_DATA_FAILURE = 'REQ_WEATHER_DATA_FAILURE';

export { REQ_WEATHER_DATA, REQ_WEATHER_DATA_SUCCESS, REQ_WEATHER_DATA_FAILURE };
